FROM eclipse-temurin:17-jdk-alpine as build
WORKDIR /app
COPY demo/pom.xml .
COPY demo/src ./src
RUN apk add --no-cache maven && \
    mvn -q -e -DskipTests package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
